
const DBHANDLER_USER_CONNECTION_OK              =   "MongoUserConnected";
const DBHANDLER_USER_CONNECTION_FAILED          =   "MongoUsertConnectionERROR";


module.exports = {

DBHANDLER_USER_CONNECTION_OK            : DBHANDLER_USER_CONNECTION_OK ,
DBHANDLER_USER_CONNECTION_FAILED        : DBHANDLER_USER_CONNECTION_FAILED

};