
const DBHANDLER_USER_CONNECTION_OK              =   "MongoUserConnected";
const DBHANDLER_USER_CONNECTION_FAILED          =   "MongoUserConnectionERROR";
const DBHANDLER_SWIMMINGPOOL_CONNECTION_OK              =   "MongoSwimmingPoolConnected";
const DBHANDLER_SWIMMINGPOOL_CONNECTION_FAILED          =   "MongoSwimmingPoolConnectionERROR";

module.exports = {

DBHANDLER_USER_CONNECTION_OK            : DBHANDLER_USER_CONNECTION_OK ,
DBHANDLER_USER_CONNECTION_FAILED        : DBHANDLER_USER_CONNECTION_FAILED,

DBHANDLER_SWIMMINGPOOL_CONNECTION_OK        : DBHANDLER_SWIMMINGPOOL_CONNECTION_OK,
DBHANDLER_SWIMMINGPOOL_CONNECTION_FAILED    :DBHANDLER_SWIMMINGPOOL_CONNECTION_FAILED

};